staff = [ ["A. Sandhya Rani", "Convenor", "../static/images/img_avatar.png"],
          ["Vijaya Lakshmi", "Staff Coorinator", "../static/images/img_avatar.png"]]

chiefs = [ ["Anukruti Jamalpur", "Chief Coordinator", "../static/images/img_avatar.png"], 
           ["", "", "../static/images/img_avatar.png"],
           ["", "", "../static/images/img_avatar.png"] ]

seniors = [ ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"]
]

juniors = [ ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
            ["", "", "../static/images/img_avatar.png"],
]